-- Vendit E-commerce 2.0 integration tables (isolated from core ecommerce schema)
USE gsmstunter;

CREATE TABLE IF NOT EXISTS vendit_customers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_number VARCHAR(50) NOT NULL,
  creation_datetime DATETIME NULL,
  transactions_blocked TINYINT(1) NOT NULL DEFAULT 0,
  company_name VARCHAR(255) NULL,
  kvk_number VARCHAR(50) NULL,
  vat_number VARCHAR(50) NULL,
  iban_number VARCHAR(64) NULL,
  allow_on_account TINYINT(1) NOT NULL DEFAULT 0,
  fixed_raise_percentage DECIMAL(10,4) NULL,
  fixed_discount_percentage DECIMAL(10,4) NULL,
  term_of_payment VARCHAR(120) NULL,
  pricelist_name VARCHAR(120) NULL,
  opt_in TINYINT(1) NOT NULL DEFAULT 0,
  opt_in_date DATETIME NULL,
  title VARCHAR(50) NULL,
  first_name VARCHAR(120) NULL,
  middle_name VARCHAR(120) NULL,
  last_name VARCHAR(120) NULL,
  sex VARCHAR(30) NULL,
  birthdate DATETIME NULL,
  email VARCHAR(180) NULL,
  phone VARCHAR(60) NULL,
  mobile VARCHAR(60) NULL,
  street VARCHAR(255) NULL,
  zip_code VARCHAR(20) NULL,
  house_number VARCHAR(20) NULL,
  house_number_suffix VARCHAR(20) NULL,
  city VARCHAR(120) NULL,
  country VARCHAR(120) NULL,
  country_code CHAR(2) NULL,
  source_format ENUM('CustomerExport', 'CustomerImport') NOT NULL DEFAULT 'CustomerExport',
  xml_hash CHAR(64) NULL,
  last_imported_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vendit_customers_number (customer_number),
  KEY idx_vendit_customers_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_customer_groups (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  group_name VARCHAR(120) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vendit_cg_customer FOREIGN KEY (customer_id) REFERENCES vendit_customers(id) ON DELETE CASCADE,
  UNIQUE KEY uq_vendit_cg_customer_group (customer_id, group_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_customer_addresses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  customer_id BIGINT UNSIGNED NOT NULL,
  address_type_description VARCHAR(60) NOT NULL,
  street VARCHAR(255) NULL,
  zip_code VARCHAR(20) NULL,
  house_number VARCHAR(20) NULL,
  house_number_suffix VARCHAR(20) NULL,
  city VARCHAR(120) NULL,
  email_address VARCHAR(180) NULL,
  default_address TINYINT(1) NOT NULL DEFAULT 0,
  country VARCHAR(120) NULL,
  country_code CHAR(2) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vendit_ca_customer FOREIGN KEY (customer_id) REFERENCES vendit_customers(id) ON DELETE CASCADE,
  KEY idx_vendit_ca_customer (customer_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_customer_contacts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  address_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(50) NULL,
  last_name VARCHAR(120) NULL,
  first_name VARCHAR(120) NULL,
  middle_name VARCHAR(120) NULL,
  sex VARCHAR(30) NULL,
  birthdate DATETIME NULL,
  email_address VARCHAR(180) NULL,
  additional_info TEXT NULL,
  function_description VARCHAR(120) NULL,
  drivers_license_number VARCHAR(60) NULL,
  bank_account VARCHAR(60) NULL,
  department VARCHAR(120) NULL,
  iban_number VARCHAR(64) NULL,
  default_contact TINYINT(1) NOT NULL DEFAULT 0,
  opt_in TINYINT(1) NOT NULL DEFAULT 0,
  opt_in_date DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_vendit_cc_address FOREIGN KEY (address_id) REFERENCES vendit_customer_addresses(id) ON DELETE CASCADE,
  KEY idx_vendit_cc_address (address_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_customer_phones (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  address_id BIGINT UNSIGNED NULL,
  contact_id BIGINT UNSIGNED NULL,
  phone_number VARCHAR(60) NOT NULL,
  dialing_code VARCHAR(10) NULL,
  phone_type_description VARCHAR(60) NULL,
  default_phone TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vendit_cp_address FOREIGN KEY (address_id) REFERENCES vendit_customer_addresses(id) ON DELETE CASCADE,
  CONSTRAINT fk_vendit_cp_contact FOREIGN KEY (contact_id) REFERENCES vendit_customer_contacts(id) ON DELETE CASCADE,
  KEY idx_vendit_cp_address (address_id),
  KEY idx_vendit_cp_contact (contact_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_orders (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_number VARCHAR(50) NOT NULL,
  store_number VARCHAR(50) NULL,
  order_type VARCHAR(30) NOT NULL DEFAULT 'Order',
  order_date DATETIME NOT NULL,
  delivery_date DATETIME NULL,
  total_order_amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  payment_method VARCHAR(60) NULL,
  payment_costs DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  paid DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  shipping_method VARCHAR(60) NULL,
  shipping_costs DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  invoice_discount_name VARCHAR(120) NULL,
  invoice_discount_amount DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  invoice_title VARCHAR(20) NULL,
  invoice_first_name VARCHAR(120) NULL,
  invoice_middle_name VARCHAR(120) NULL,
  invoice_last_name VARCHAR(120) NULL,
  invoice_email VARCHAR(180) NULL,
  invoice_phone VARCHAR(60) NULL,
  invoice_phone_mobile VARCHAR(60) NULL,
  invoice_address VARCHAR(255) NULL,
  invoice_housenumber VARCHAR(20) NULL,
  invoice_housenumber_extension VARCHAR(20) NULL,
  invoice_zipcode VARCHAR(20) NULL,
  invoice_city VARCHAR(120) NULL,
  invoice_country VARCHAR(120) NULL,
  invoice_country_code CHAR(2) NULL,
  company_name VARCHAR(255) NULL,
  iban_number VARCHAR(64) NULL,
  bank_account VARCHAR(60) NULL,
  vat_number VARCHAR(50) NULL,
  opt_in TINYINT(1) NULL,
  opt_in_date DATETIME NULL,
  order_status_id INT NULL,
  delivery_title VARCHAR(20) NULL,
  delivery_first_name VARCHAR(120) NULL,
  delivery_middle_name VARCHAR(120) NULL,
  delivery_last_name VARCHAR(120) NULL,
  delivery_address VARCHAR(255) NULL,
  delivery_housenumber VARCHAR(20) NULL,
  delivery_housenumber_extension VARCHAR(20) NULL,
  delivery_zipcode VARCHAR(20) NULL,
  delivery_city VARCHAR(120) NULL,
  delivery_country VARCHAR(120) NULL,
  delivery_country_code CHAR(2) NULL,
  delivery_company_name VARCHAR(255) NULL,
  order_remark TEXT NULL,
  order_message TEXT NULL,
  additional_order_info TEXT NULL,
  gift TINYINT(1) NULL,
  gift_message TEXT NULL,
  invoice_ex_vat TINYINT(1) NOT NULL DEFAULT 0,
  default_address TINYINT(1) NULL,
  customer_number VARCHAR(50) NULL,
  office_id INT NULL,
  employee_id INT NULL,
  order_priority_id INT NULL,
  customer_group VARCHAR(120) NULL,
  order_origin VARCHAR(120) NULL,
  export_status ENUM('pending', 'exported', 'failed') NOT NULL DEFAULT 'pending',
  export_file_path VARCHAR(500) NULL,
  exported_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_vendit_orders_number (order_number),
  KEY idx_vendit_orders_export_status (export_status),
  KEY idx_vendit_orders_customer_number (customer_number)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_order_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  order_id BIGINT UNSIGNED NOT NULL,
  ecommerce_product_guid CHAR(36) NULL,
  product_id VARCHAR(60) NULL,
  ean VARCHAR(32) NULL,
  product_sales_price_ex DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  product_sales_price_inc DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  private_copy_levy DECIMAL(14,4) NOT NULL DEFAULT 0.0000,
  quantity DECIMAL(14,4) NOT NULL DEFAULT 1.0000,
  remarks TEXT NULL,
  office_id INT NULL,
  reserve_stock TINYINT(1) NULL,
  description VARCHAR(500) NULL,
  is_dropshipment TINYINT(1) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_vendit_oi_order FOREIGN KEY (order_id) REFERENCES vendit_orders(id) ON DELETE CASCADE,
  KEY idx_vendit_oi_order (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS vendit_sync_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  sync_type VARCHAR(60) NOT NULL,
  direction ENUM('import', 'export') NOT NULL,
  file_name VARCHAR(255) NULL,
  file_path VARCHAR(500) NULL,
  status ENUM('started', 'success', 'failed', 'partial') NOT NULL DEFAULT 'started',
  records_processed INT UNSIGNED NOT NULL DEFAULT 0,
  records_failed INT UNSIGNED NOT NULL DEFAULT 0,
  message TEXT NULL,
  validation_status ENUM('unknown', 'valid', 'invalid') NOT NULL DEFAULT 'unknown',
  validation_errors JSON NULL,
  started_at DATETIME NOT NULL,
  completed_at DATETIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  KEY idx_vendit_sync_logs_type (sync_type),
  KEY idx_vendit_sync_logs_started (started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
